# Use the newer container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python

python:
    - 2.7
    - 3.5
    - 3.6

env:
    - DJANGO=Django==1.11.13 OSCAR=django-oscar==1.5.4
    - DJANGO=Django==2.0.5 OSCAR=django-oscar==1.6

matrix:
  exclude:
    - python: 2.7
      env: DJANGO=Django==2.0.5 OSCAR=django-oscar==1.6

before_install:
    - pip install codecov

install:
    - pip install $OSCAR
    - if [ ${DJANGO} == "Django==2.0.5" ]; then pip install "djangorestframework>=3.7"; fi
    - make install

script:
    - make coverage

after_success:
  - codecov
