language: python

dist: xenial

matrix:
  include:
    - { python: "3.5", env: "DJANGO='Django>=2.1,<2.2' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"}
    - { python: "3.6", env: "DJANGO='Django>=2.1,<2.2' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"}
    - { python: "3.7", env: "DJANGO='Django>=2.1,<2.2' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"}

    - { python: "3.5", env: "DJANGO='Django>=2.2,<3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"}
    - { python: "3.6", env: "DJANGO='Django>=2.2,<3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"}
    - { python: "3.7", env: "DJANGO='Django>=2.2,<3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"}

before_install:
    - pip install codecov

install:
    - pip install $OSCAR $DJANGO
    - make install
    - pip freeze

script:
    - make coverage

after_success:
  - codecov
