# Use the newer container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Cache pip downloads
cache:
    directories:
      - $HOME/.pip-cache/

language: python

python:
    - '2.7.13'
    - '3.5'
    - '3.6'

env:
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.2.2
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.3
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.4
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.5
    - DJANGO=Django==1.10.8 OSCAR=django-oscar==1.4
    - DJANGO=Django==1.10.8 OSCAR=django-oscar==1.5
    - DJANGO=Django==1.11.7 OSCAR=django-oscar==1.5

before_install:
    - pip install codecov

install:
    - pip install $OSCAR
    # django rest framework 3.7+ is not compatible with django 1.8
    - if [ ${DJANGO} == "Django==1.8.19" ]; then pip install "djangorestframework<3.7"; fi
    # because there are some dependency issues with oscar and haystack
    - if [ ${DJANGO} == "Django==1.11.7" ]; then pip install $DJANGO -e .[django_1_11]; else pip install $DJANGO -e .; fi
    - make install

script:
    - make coverage

after_success:
  - codecov
