# Use the newer container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python

python:
    - 2.7
    - 3.5
    - 3.6

env:
    - DJANGO='Django<2.0' OSCAR='django-oscar<1.6'
    - DJANGO='Django<2.0' OSCAR='django-oscar<1.7'
    - DJANGO='Django<2.1' OSCAR='django-oscar<1.7'
    - DJANGO='Django<2.2' OSCAR='django-oscar<1.7'

matrix:
  exclude:
    - python: 2.7
      env: DJANGO='Django<2.1' OSCAR='django-oscar<1.7'
    - python: 2.7
      env: DJANGO='Django<2.2' OSCAR='django-oscar<1.7'

before_install:
    - pip install codecov

install:
    - pip install $OSCAR $DJANGO
    - if ! [ ${DJANGO} == "Django<2.0" ]; then pip install "djangorestframework>=3.7"; fi
    - pip freeze
    - make install

script:
    - make coverage

after_success:
  - codecov
