# Use the newer container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Cache pip downloads
cache:
    directories:
      - $HOME/.pip-cache/

language: python

python:
    - '2.7'
    - '3.5'

env:
    - DJANGO=Django==1.7.11
    - DJANGO=Django==1.8.7
    - DJANGO=Django==1.9
matrix:
    exclude:
        - python: "3.5"
          env: DJANGO=Django==1.7.11

before_install:
    - pip install codecov

install:
    - pip install $DJANGO -e . --download-cache $HOME/.pip-cache

script:
    - make coverage

after_success:
  - codecov