# Use the newer container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Cache pip downloads
cache:
    directories:
      - $HOME/.pip-cache/

language: python

python:
    - '2.7.13'
    - '3.5'
    - '3.6'

env:
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.2.2
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.3
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.4
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.5.1
    - DJANGO=Django==1.10.8 OSCAR=django-oscar==1.4
    - DJANGO=Django==1.10.8 OSCAR=django-oscar==1.5.1
    - DJANGO=Django==1.11.8 OSCAR=django-oscar==1.5.1

before_install:
    - pip install codecov

install:
    - pip install $OSCAR
    # django rest framework 3.7+ and django-tables2 1.17+ are not compatible with django 1.8
    - if [ ${DJANGO} == "Django==1.8.18" ]; then pip install "djangorestframework<3.7"; pip install "django-tables2<1.17.0"; fi
    - make install

script:
    - make coverage

after_success:
  - codecov
